version: '3'
services:
  rabbitmq:
    build: rabbitmq
    container_name: "odonto-delta-deps-rabbitmq"
    labels:
      kompose.service.type: nodeport
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    volumes:
      - 'rabbitmq_data:/bitnami'
    environment:
          - RABBITMQ_DEFAULT_USER=guest
          - RABBITMQ_DEFAULT_PASS=guest
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainerdata:/data"
volumes:
  portainerdata: null
  rabbitmq_data:
    driver: local
networks:
  default:
    external:
      name: siganet