server:
  port:5050
application:
  version: @project.version@
  name: odonto-delta
  default-logo-path: /img/logo.png
spring:
  jpa:
    database: postgresql
    show-sql: true
  datasource:
    platform: org.hibernate.dialect.PostgreSQLDialect
    url: jdbc:postgresql://localhost:5432/molens
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  application:
    name: odonto-delta
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true