application:
  version: @project.version@
  name: odonto-delta-api
  default-logo-path: /img/logo.png
spring:
  application:
    name: odonto-delta-api
  liquibase:
    change-log: classpath:migration/master.xml
    liquibase-schema: odonto
    default-schema: odonto
    contexts: ${LIQUIBASE_CONTEXTS}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_CLASSNAME}
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}